### ISSUE TITLE
Licence text is 404

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon-scans/documentation#1]
I guess it applies to all scans repositories. 
Maybe the website from which licence file used to be fetched by some script, has moved it somewhere else.

**Comment by funderburkjim** [comment]
Apparently I put this repository with good intentions of documenting usage of the other repositories in the th sanskrit-lexicon-scans organization. But  this sanskrit-lexicon-scans/documentation repository is currently only a stub.

**Comment by drdhaval2785** [comment]
Not only this, all repositories in sanskrit-lexicon-scans are showing this 404 error.

**Comment by drdhaval2785** [comment]
All of them require to be corrected.

**Comment by funderburkjim** [comment]
I deleted the LICENSE file in each repository.

The README.md file for each repository has a Creative Commons license mention.

![image](https://user-images.githubusercontent.com/6393033/135931965-9749e72c-0ea3-4325-83fc-ad32479e75d6.png)
